# Generated by Django 4.2.1 on 2023-05-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lastname', models.CharField(max_length=150)),
                ('Firstname', models.CharField(max_length=150)),
                ('Midname', models.CharField(blank=True, max_length=150, null=True)),
                ('Extname', models.CharField(blank=True, max_length=150, null=True)),
                ('Civilstatus', models.CharField(max_length=25)),
            ],
        ),
    ]
