# Generated by Django 4.2.1 on 2023-05-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lastname', models.CharField(max_length=150)),
                ('Firstname', models.CharField(max_length=150)),
                ('Midname', models.CharField(blank=True, max_length=150, null=True)),
                ('Extname', models.CharField(blank=True, max_length=150, null=True)),
                ('Civilstatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='employees',
            name='Civilstatus',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=25),
        ),
    ]
