# Generated by Django 4.2.1 on 2023-05-17 08:24

import birthday.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_instructor_alter_employees_civilstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='bday',
            field=birthday.fields.BirthdayField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='bday_dayofyear_internal',
            field=models.PositiveSmallIntegerField(default=None, editable=False, null=True),
        ),
    ]
